name: 00.hello work workflow

on:
    push:
        branches:
            - main


jobs:
    say-hello:
        runs-on: ubuntu-latest

        steps:
            - name: Print Hello world
              run: echo "Hello, World"

            - name: Run a custom script
              run: |
                echo "This is custom script"
                mkdir -p ny_directory
                echo "Script executrd successfully"
