name: 01.nodejs pipeline

on:
    push:
        branches:
            - main


jobs:
    buid:
        runs-on: ubuntu-latest


        steps:
            - name: Checkout code
              uses: actions/checkout@v3 

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18.x

            - name: Install dependencies with npm
              run: npm install
              working-directory: modules/01.Nodejs_Pipeline
              continue-on-error: false
              id: install-dependencies

            - name: Run ESLint
              run: npm run lint
              working-directory: modules/01.Nodejs_Pipeline
              continue-on-error: false
              id: run-eslint

            - name: Run Jest tests
              run: npm test
              working-directory: modules/01.Nodejs_Pipeline
              continue-on-error: false
              id: run-tests

            - name: Install Railway CLI
              run: npm i -g @railway/cli
              working-directory: modules/01.Nodejs_Pipeline
              continue-on-error: false
              id: install-railway-cli

            - name: Deploy to Railway
              run: railway up --service GHA-Node
              env:
                RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
              working-directory: modules/01.Nodejs_Pipeline
              continue-on-error: false
              id: deploy-to-railway

              # success/failure msg
            - name: Check Success/Failure Message
              if: always()
              run: |
                if [ ${{ steps.install-dependencies.outcome}} == 'success' ]; then
                    echo "✅ Dependencies installed successfully!"
                 else
                    echo "❌ Failed to install dependencies!"
                    exit 1
                fi

                
                if [ ${{ steps.run-eslint.outcome}} == 'success' ]; then
                    echo "✅ Dependencies installed successfully!"
                 else
                    echo "❌ Failed to install dependencies!"
                    exit 1
                fi

                
                if [ ${{ steps.run-tests.outcome}} == 'success' ]; then
                    echo "✅ Dependencies installed successfully!"
                 else
                    echo "❌ Failed to install dependencies!"
                    exit 1
                fi

                if [ ${{ steps.install-railway-cli.outcome}} == 'success' ]; then
                    echo "✅ Dependencies installed successfully!"
                 else
                    echo "❌ Failed to install dependencies!"
                    exit 1
                fi

                if [ ${{ steps.deploy-to-railway.outcome}} == 'success' ]; then
                    echo "✅ Dependencies installed successfully!"
                 else
                    echo "❌ Failed to install dependencies!"
                    exit 1
                fi
                

         
                

            




            

           
              
              

         


            
              