name: 03.deploy flask to render

on:
    push:
        branches:
            - main

jobs:
    deploy-flask:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.9'

            - name: Install Dependencies
              run: |
                 python -m pip install --upgrade pip
                 pip install -r requirements.txt
              continue-on-error: false
              working-directory: modules/03.Python_Flask_Pipeline


            - name: Run Flake8 Linting
              run: flake8 .
              continue-on-error: false
              working-directory: modules/03.Python_Flask_Pipeline

            - name: Py test
              run: pytest test_app.py
              continue-on-error: false
              working-directory: modules/03.Python_Flask_Pipeline

              

           